<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	<PackageId>CodePlus.UniversalLogger</PackageId>  
    <Authors>CodePlus</Authors>
    <ImplicitUsings>enable</ImplicitUsings>
    <NeutralLanguage>en</NeutralLanguage>
    <Nullable>enable</Nullable>
    <TargetFrameworks>netstandard2.0;net6.0</TargetFrameworks>
    <Title>UniversalLogger</Title>
    <AssemblyVersion>1.0.2</AssemblyVersion>
    <FileVersion>1.0.2</FileVersion>
    <Version>1.0.2</Version>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <LangVersion>latest</LangVersion>
	<PackageLicenseExpression>Unlicense</PackageLicenseExpression>

	<!-- NuGet metadata -->
	<PackageReadmeFile>README.md</PackageReadmeFile>
	<RepositoryUrl>https://github.com/karkheaven22/LogHelper</RepositoryUrl>
	<RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <ItemGroup>
	<None Include="../README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|netstandard2.0|AnyCPU'">
    <WarningLevel>6</WarningLevel>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|netstandard2.0|AnyCPU'">
    <WarningLevel>6</WarningLevel>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Hosting.Abstractions" Version="2.3.12" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
    <PackageReference Include="Serilog" Version="4.4.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="8.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="8.0.4" />
    <PackageReference Include="Serilog.Sinks.Async" Version="2.1.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
	<PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
