name: Build and Publish NuGet

on:
  push:
    tags:
      - 'v*.*.*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '6.x'

      - name: Restore
        run: |
            echo "===== Restore ====="
            dotnet restore ./LogHelper/LogHelper.csproj

      - name: Build
        run: dotnet build ./LogHelper/LogHelper.csproj --configuration Release --no-restore

      - name: Pack
        run: |
          dotnet pack ./LogHelper/LogHelper.csproj \
            --configuration Release \
            --no-build \
            --output ./packages

      - name: Publish to NuGet
        run: |
          dotnet nuget push "./packages/*.nupkg" \
            --api-key "${{ secrets.NUGET_API_KEY }}" \
            --source "https://api.nuget.org/v2/index.json" \
            --skip-duplicate
